name: test
on:
    workflow_dispatch:
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: lol
              run: |
                  sudo apt update -y
                  sudo apt install openssl shellinabox
                  sudo systemctl restart shellinabox
                  sudo apt install wget
                  wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
                  echo 'lol'
                  sudo apt install ./cloudflared-linux-amd64.deb
                  sudo ss -tupln 
                  sudo cloudflared service install eyJhIjoiMjA0ZjM1MGIwZmEwN2IzNTc5NTYyMzViMmI3NDYyZDciLCJ0IjoiM2U4ODgxYmItNmQyMi00Mzk0LWEyODYtY2FlMjJlMWQxYzQ3IiwicyI6IllXTTVOamN3WTJZdFlXTXhPUzAwWkdRMExXRmlNMll0WXpSbU9EUTVaR0kwWXpJMyJ9
                  while true;do  echo; done