name: test
on:
    workflow_dispatch:
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: lol
              run: |
                  sudo apt update -y
                  sudo apt install openssh-client wget openssl shellinabox nodejs npm
                  sudo systemctl restart shellinabox
                  sudo ss -tupln 
                  npm install -g @hrzn/cli
                  hrzn login f778a47a-6c2a-4455-8db5-3cbe51e95995
                  hrzn tunnel https://localhost:4200
                  while true;do  echo; done