name: test
on:
    workflow_dispatch:
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: lol
              run: |
                  sudo apt update -y
                  sudo apt install openssh-client shellinabox openssh
                  sudo systemctl status shellinabox
                  ssh -o "StrictHostKeyChecking no" -p 443 -R0:localhost:4200 a.pinggy.io
                  
                  