name: test
on:
    workflow_dispatch:
jobs:
    download:
        runs-on: ubuntu-latest
        steps:
            - name: lol
              run: |
                  sudo apt update -y
                  sudo apt install openssh-client wget openssl shellinabox
                  sudo systemctl restart shellinabox
                  sudo ss -tupln 
                  wget https://openport.io/download/debian64/latest.deb
                  sudo dpkg -i latest.deb
                  sudo openport register-key jc8sRyaobu
                  openport 4200 --http-forward
                  while true;do  echo; done